# Matching users as client of EvasionBuilder and MatchingUsers modules

In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
%matplotlib inline
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from importlib import reload
import datetime as dt
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
from Utils import TransantiagoConstants
import EvasionBuilder

In [4]:
processed_evasion = EvasionBuilder.runCompleteProcess()

Original number of rows in complete evasion database is: 97373
Number of duplicated rows in complete evasion database is: 6192
Number of collapsed-duplicated rows in complete evasion database is: 3090
Number of rows in complete evasion database without duplicated rows at all is: 91181
Final number of rows in complete evasion database with collapsed duplicated rows is: 94271

C:\Users\leoca_000\Anaconda3\lib\site-packages\pandas\core\indexing.py:337: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
C:\Users\leoca_000\Anaconda3\lib\site-packages\pandas\core\indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

The only non-matched user_code services are:
D06

* Processing complete evasion-ddbb

In [5]:
evasion_paradero = processed_evasion[processed_evasion['TP']=='P']
evasion_paradero_first = evasion_paradero[evasion_paradero['N_PUERTA']==1]

In [6]:
print('Number of rows in complete evasion database is: ' + str(len(processed_evasion.index)))
print('Number of rows in evasion in paradero database is: ' + str(len(evasion_paradero.index)))
print('Number of rows in evasion in paradero by first door database is: ' + str(len(evasion_paradero_first.index)))

Number of rows in complete evasion database is: 94271
Number of rows in evasion in paradero database is: 92604
Number of rows in evasion in paradero by first door database is: 33120

* Filtering dates not in common dates. DataFrame "common_dates_evasion" will be the final evasion DataFrame

In [7]:
common_dates = TransantiagoConstants.common_dates
common_dates_timestamp = [pd.to_datetime(x) for x in common_dates]
common_dates_evasion = evasion_paradero_first[evasion_paradero_first['FECHA'].isin(common_dates_timestamp)]

print('Number of rows in complete evasion database filtered by common_dates is: ' + str(len(common_dates_evasion.index))) #Remember to store the number.

Number of rows in complete evasion database filtered by common_dates is: 14632

* Building Etapas DataBase via <strong>RunSilentlyDailyEtapasBuilder</strong> and matching users via <strong>MatchingUsers</strong>

In [8]:
common_dates = common_dates[:1]
#common_dates = ['2017-04-11']

In [9]:
from RunSilentlyDailyEtapasBuilder import RunSilentlyDailyEtapasBuilderClass

In [10]:
import MatchingUsers

In [18]:
summary_evasion_vs_mean = pd.DataFrame()

for date in common_dates:    
    etapas_builder = RunSilentlyDailyEtapasBuilderClass(date) #Critical.
    #Should I work with processed_sorted_df or with filtered_sorted_df...? => with processed_sorted_df as I see all the stops along the lines.
    processed_sorted_df = etapas_builder.runProcessedProcess()    
    processed_sorted_df['sitio_subida'] = processed_sorted_df['sitio_subida'].str.replace("-", "")
    processed_sorted_df['sitio_subida'] = processed_sorted_df['sitio_subida'].str.replace(" ", "")
    
    processed_sorted_df['servicio_subida'] =  processed_sorted_df['servicio_subida'].str.replace('T','')
    processed_sorted_df['servicio_subida'] =  processed_sorted_df['servicio_subida'].str.split(' ').str[0]
    
    [evasion_by_date, patentes_by_date, servicios_by_date] = MatchingUsers.simplifyingEvasion(common_dates_evasion,date) #Getting patentes and servicios surveyed in date...
    
    clean_sorted_df = processed_sorted_df[(processed_sorted_df['sitio_subida'].isin(patentes_by_date))&(processed_sorted_df['servicio_subida'].isin(servicios_by_date))] #Filtering...
    clean_sorted_df = clean_sorted_df.reset_index(drop=True)
#    clean_sorted_df = clean_sorted_df[(clean_sorted_df['diferencia_tiempo_secs']<=20)] #This deletes the NaN rows
    
    clean_sorted_df = MatchingUsers.appendingIdExpedicion(clean_sorted_df) #Appending (ad-hoc) id expedicion.
    grouped_clean_sorted_df_1 = MatchingUsers.groupByEtapasDatabase(clean_sorted_df) #Grouping by 'sitio_subida','servicio_subida','idExpedicion','par_subida'
    grouped_clean_sorted_df_2 = MatchingUsers.appendingStartEndCuts(grouped_clean_sorted_df_1) #Computing start and end cuts.
    grouped_clean_sorted_df_3 = MatchingUsers.slicingEvasionDatabase(grouped_clean_sorted_df_2,evasion_by_date) #This is the final ddbb with full info.
    summary_evasion_vs_mean = pd.concat([summary_evasion_vs_mean,grouped_clean_sorted_df_3])

Not found in turnstile database: 1795630
Not found in turnstile database: 1832615
Not found in turnstile database: 1842842

In [12]:
len(summary_evasion_vs_mean.index)

2969

In [17]:
clean_sorted_df.describe()

,index,id,nviaje,diferencia_tiempo,diferencia_tiempo_secs
count,5.373000e+03,5.373000e+03,5373.000000,5373,5373.000000
mean,1.335347e+06,2.203220e+09,1.808859,0 days 00:00:03.829517,3.829518
std,7.651234e+05,1.307530e+09,1.031043,0 days 00:00:03.203853,3.203853
min,2.690000e+02,1.854236e+07,1.000000,0 days 00:00:00,0.000000
25%,6.742680e+05,9.326554e+08,1.000000,0 days 00:00:02,2.000000
50%,1.352763e+06,2.511356e+09,2.000000,0 days 00:00:03,3.000000
75%,1.992149e+06,3.308773e+09,2.000000,0 days 00:00:04,4.000000
max,2.651533e+06,4.288362e+09,12.000000,0 days 00:00:20,20.000000

In [19]:
clean_sorted_df.head(50)

,index,id,nviaje,tipo_transporte,t_subida,servicio_subida,par_subida,sitio_subida,fecha_instalacion,mismo_paradero,misma_patente,mismo_servicio,diferencia_tiempo,diferencia_tiempo_secs,si_torniquete,si_2017_torniquete,idExpedicion
0,781576,1235005144,3,BUS,2017-03-15 12:29:06,508,L-32-10-10-OP,BDXR41,NaT,False,True,False,NaT,NaN,False,False,1
1,1368533,2512673838,3,BUS,2017-03-15 12:29:09,508,L-32-10-10-OP,BDXR41,NaT,True,True,True,00:00:03,3.0,False,False,1
2,678920,932889035,1,BUS,2017-03-15 12:29:11,508,L-32-10-10-OP,BDXR41,NaT,True,True,True,00:00:02,2.0,False,False,1
3,1805482,3138900494,1,BUS,2017-03-15 12:32:05,508,L-32-33-75-SN,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
4,2580317,4019534075,1,BUS,2017-03-15 12:37:25,508,L-32-19-35-OP,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
5,1451062,2628110302,1,BUS,2017-03-15 12:37:28,508,L-32-19-35-OP,BDXR41,NaT,True,True,True,00:00:03,3.0,False,False,1
6,1084357,2115592408,3,BUS,2017-03-15 12:38:33,508,L-32-19-25-OP,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
7,1206760,2418821403,2,BUS,2017-03-15 12:38:34,508,L-32-19-25-OP,BDXR41,NaT,True,True,True,00:00:01,1.0,False,False,1
8,1774355,3128688974,1,BUS,2017-03-15 12:39:37,508,L-32-19-15-OP,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
9,2280132,3573994200,1,BUS,2017-03-15 12:41:53,508,L-31-6-10-OP,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
10,979850,1805483950,1,BUS,2017-03-15 12:50:05,508,T-18-378-SN-3,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
11,2234172,3569033755,2,BUS,2017-03-15 12:51:40,508,T-18-378-SN-10,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
12,1261273,2474505758,1,BUS,2017-03-15 12:51:43,508,T-18-378-SN-10,BDXR41,NaT,True,True,True,00:00:03,3.0,False,False,1
13,2182113,3560556254,3,BUS,2017-03-15 12:51:47,508,T-18-378-SN-10,BDXR41,NaT,True,True,True,00:00:04,4.0,False,False,1
14,2336338,3644685796,1,BUS,2017-03-15 12:54:24,508,T-18-156-OP-25,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
15,1470500,2641454830,2,BUS,2017-03-15 12:54:27,508,T-18-156-OP-25,BDXR41,NaT,True,True,True,00:00:03,3.0,False,False,1
16,409912,422501426,2,BUS,2017-03-15 12:54:30,508,T-18-156-OP-25,BDXR41,NaT,True,True,True,00:00:03,3.0,False,False,1
17,1041394,2012744064,2,BUS,2017-03-15 12:56:27,508,T-18-156-OP-38,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
18,1202759,2397715051,2,BUS,2017-03-15 12:56:29,508,T-18-156-OP-38,BDXR41,NaT,True,True,True,00:00:02,2.0,False,False,1
19,1371237,2513823694,2,BUS,2017-03-15 12:56:31,508,T-18-156-OP-38,BDXR41,NaT,True,True,True,00:00:02,2.0,False,False,1
20,50819,27448738,1,BUS,2017-03-15 12:56:32,508,T-18-156-OP-38,BDXR41,NaT,True,True,True,00:00:01,1.0,False,False,1
21,1565473,2733583358,3,BUS,2017-03-15 12:56:34,508,T-18-156-OP-38,BDXR41,NaT,True,True,True,00:00:02,2.0,False,False,1
22,1826746,3167827614,2,BUS,2017-03-15 12:56:34,508,T-18-156-OP-38,BDXR41,NaT,True,True,True,00:00:00,0.0,False,False,1
23,336883,246728534,2,BUS,2017-03-15 12:56:38,508,T-18-156-OP-38,BDXR41,NaT,True,True,True,00:00:04,4.0,False,False,1
24,1458835,2638825742,2,BUS,2017-03-15 12:56:40,508,T-18-156-OP-38,BDXR41,NaT,True,True,True,00:00:02,2.0,False,False,1
25,1847959,3169085614,1,BUS,2017-03-15 12:56:43,508,T-18-156-OP-38,BDXR41,NaT,True,True,True,00:00:03,3.0,False,False,1
26,2057902,3466815940,1,BUS,2017-03-15 12:56:50,508,T-18-156-OP-38,BDXR41,NaT,True,True,True,00:00:07,7.0,False,False,1
27,352170,261560150,1,BUS,2017-03-15 12:56:52,508,T-18-156-OP-38,BDXR41,NaT,True,True,True,00:00:02,2.0,False,False,1
28,2014565,3323261998,2,BUS,2017-03-15 12:56:52,508,T-18-156-OP-38,BDXR41,NaT,True,True,True,00:00:00,0.0,False,False,1
29,1992450,3309581274,2,BUS,2017-03-15 12:56:55,508,T-18-156-OP-38,BDXR41,NaT,True,True,True,00:00:03,3.0,False,False,1
30,335673,243645222,1,BUS,2017-03-15 12:58:03,508,T-18-156-OP-45,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
31,1282894,2501105902,1,BUS,2017-03-15 12:58:03,508,T-18-156-OP-45,BDXR41,NaT,True,True,True,00:00:00,0.0,False,False,1
32,83617,44086290,2,BUS,2017-03-15 12:59:51,508,T-18-156-OP-50,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
33,1754788,3066199451,1,BUS,2017-03-15 12:59:56,508,T-18-156-OP-50,BDXR41,NaT,True,True,True,00:00:05,5.0,False,False,1
34,1771462,3126458484,1,BUS,2017-03-15 13:03:51,508,T-18-156-OP-60,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
35,148745,57956354,2,BUS,2017-03-15 13:03:55,508,T-18-156-OP-60,BDXR41,NaT,True,True,True,00:00:04,4.0,False,False,1
36,180740,95054418,1,BUS,2017-03-15 13:03:58,508,T-18-156-OP-60,BDXR41,NaT,True,True,True,00:00:03,3.0,False,False,1
37,2444866,3915347099,1,BUS,2017-03-15 13:04:00,508,T-18-156-OP-60,BDXR41,NaT,True,True,True,00:00:02,2.0,False,False,1
38,1043408,2025530426,2,BUS,2017-03-15 13:04:02,508,T-18-156-OP-60,BDXR41,NaT,True,True,True,00:00:02,2.0,False,False,1
39,2320392,3612141668,3,BUS,2017-03-15 13:09:58,508,T-18-130-SN-5,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
40,592161,859399114,1,BUS,2017-03-15 13:10:44,508,T-18-130-SN-10,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
41,381710,419998930,1,BUS,2017-03-15 13:11:22,508,T-18-130-SN-15,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
42,1245571,2461851866,2,BUS,2017-03-15 13:11:24,508,T-18-130-SN-15,BDXR41,NaT,True,True,True,00:00:02,2.0,False,False,1
43,2169292,3554284062,2,BUS,2017-03-15 13:14:34,508,T-14-130-SN-10,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
44,1333121,2506666110,1,BUS,2017-03-15 13:14:39,508,T-14-130-SN-10,BDXR41,NaT,True,True,True,00:00:05,5.0,False,False,1
45,2190627,3561779838,2,BUS,2017-03-15 13:17:08,508,T-14-130-SN-15,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
46,644590,930893019,1,BUS,2017-03-15 13:18:44,508,T-14-130-SN-20,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
47,1009585,1912692068,1,BUS,2017-03-15 13:18:53,508,T-14-130-SN-20,BDXR41,NaT,True,True,True,00:00:09,9.0,False,False,1
48,2395463,3861633579,3,BUS,2017-03-15 13:25:26,508,E-20-192-OP-5,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1
49,1857758,3169667822,2,BUS,2017-03-15 13:32:59,508,T-20-73-OP-10,BDXR41,NaT,False,True,True,NaT,NaN,False,False,1

In [20]:
summary_evasion_vs_mean.head(50)

,sitio_subida,servicio_subida,idExpedicion,par_subida,t_subidamin,t_subidamax,t_subidacount,diferencia_tiempo_secsmean,start_cut,end_cut,count_ev_obs,ingresan,no_validan
0,BKWK90,F05,1,L-34-54-115-SN,2017-03-09 07:04:25,2017-03-09 07:04:25,1,NaN,2017-03-09 07:03:55,2017-03-09 07:04:46.500000,0.0,0.0,0.0
1,BKWK90,F05,1,L-34-54-100-SN,2017-03-09 07:05:08,2017-03-09 07:05:08,1,NaN,2017-03-09 07:04:46.500000,2017-03-09 07:06:45.500000,0.0,0.0,0.0
2,BKWK90,F05,1,L-34-68-40-SN,2017-03-09 07:08:23,2017-03-09 07:09:16,21,2.650000,2017-03-09 07:06:45.500000,2017-03-09 07:09:33.500000,0.0,0.0,0.0
3,BKWK90,F05,1,L-34-68-30-SN,2017-03-09 07:09:51,2017-03-09 07:10:05,8,2.000000,2017-03-09 07:09:33.500000,2017-03-09 07:10:22.500000,0.0,0.0,0.0
4,BKWK90,F05,1,L-34-68-20-SN,2017-03-09 07:10:40,2017-03-09 07:10:57,8,2.428571,2017-03-09 07:10:22.500000,2017-03-09 07:11:13.500000,0.0,0.0,0.0
5,BKWK90,F05,1,L-34-68-5-SN,2017-03-09 07:11:30,2017-03-09 07:11:47,10,1.888889,2017-03-09 07:11:13.500000,2017-03-09 07:13:00.500000,0.0,0.0,0.0
6,BKWK90,F05,1,L-34-34-50-OP,2017-03-09 07:14:14,2017-03-09 07:14:32,13,1.500000,2017-03-09 07:13:00.500000,2017-03-09 07:15:17.500000,0.0,0.0,0.0
7,BKWK90,F05,1,L-34-34-40-OP,2017-03-09 07:16:03,2017-03-09 07:16:19,3,8.000000,2017-03-09 07:15:17.500000,2017-03-09 07:16:55.500000,0.0,0.0,0.0
8,BKWK90,F05,1,L-34-34-30-OP,2017-03-09 07:17:32,2017-03-09 07:17:37,3,2.500000,2017-03-09 07:16:55.500000,2017-03-09 07:17:55,0.0,0.0,0.0
9,BKWK90,F05,1,L-34-34-20-OP,2017-03-09 07:18:13,2017-03-09 07:18:17,2,4.000000,2017-03-09 07:17:55,2017-03-09 07:19:11,0.0,0.0,0.0
10,BKWK90,F05,1,L-34-71-10-SN,2017-03-09 07:20:05,2017-03-09 07:20:08,2,3.000000,2017-03-09 07:19:11,2017-03-09 07:22:19.500000,0.0,0.0,0.0
11,BKWK90,F05,1,T-34-270-NS-10,2017-03-09 07:24:31,2017-03-09 07:24:57,6,5.200000,2017-03-09 07:22:19.500000,2017-03-09 07:26:23,0.0,0.0,0.0
12,BKWK90,F05,1,L-34-22-20-NS,2017-03-09 07:27:49,2017-03-09 07:27:49,1,NaN,2017-03-09 07:26:23,2017-03-09 07:30:41.500000,0.0,0.0,0.0
13,BKWK90,F05,1,T-34-217-OP-25,2017-03-09 07:33:34,2017-03-09 07:33:34,1,NaN,2017-03-09 07:30:41.500000,2017-03-09 07:35:06,0.0,0.0,0.0
14,BKWK90,F05,1,L-34-10-10-OP,2017-03-09 07:36:38,2017-03-09 07:36:41,2,3.000000,2017-03-09 07:35:06,2017-03-09 07:37:23,0.0,0.0,0.0
15,BKWK90,F05,1,L-34-25-5-NS,2017-03-09 07:38:05,2017-03-09 07:38:05,1,NaN,2017-03-09 07:37:23,2017-03-09 07:38:30,0.0,0.0,0.0
16,BKWK90,F05,1,L-34-9-15-SN,2017-03-09 07:38:55,2017-03-09 07:39:49,2,54.000000,2017-03-09 07:38:30,2017-03-09 07:40:11,0.0,0.0,0.0
17,BKWK90,F05,1,L-34-9-10-SN,2017-03-09 07:40:33,2017-03-09 07:40:33,1,NaN,2017-03-09 07:40:11,2017-03-09 07:41:46,0.0,0.0,0.0
18,BKWK90,F05,1,L-33-6-65-SN,2017-03-09 07:42:59,2017-03-09 07:42:59,1,NaN,2017-03-09 07:41:46,2017-03-09 07:44:23,0.0,0.0,0.0
19,BKWK90,F05,1,L-33-6-45-SN,2017-03-09 07:45:47,2017-03-09 07:45:54,2,7.000000,2017-03-09 07:44:23,2017-03-09 07:46:28,0.0,0.0,0.0
20,BKWK90,F05,1,L-33-6-35-SN,2017-03-09 07:47:02,2017-03-09 07:47:05,2,3.000000,2017-03-09 07:46:28,2017-03-09 07:47:41,0.0,0.0,0.0
21,BKWK90,F05,1,L-33-6-25-SN,2017-03-09 07:48:17,2017-03-09 07:48:20,2,3.000000,2017-03-09 07:47:41,2017-03-09 07:49:26,0.0,0.0,0.0
22,BKWK90,F05,1,L-22-30-25-OP,2017-03-09 07:50:32,2017-03-09 07:50:43,3,5.500000,2017-03-09 07:49:26,2017-03-09 07:51:21,0.0,0.0,0.0
23,BKWK90,F05,1,L-22-30-20-OP,2017-03-09 07:51:59,2017-03-09 07:51:59,1,NaN,2017-03-09 07:51:21,2017-03-09 07:52:25.500000,0.0,0.0,0.0
24,BKWK90,F05,1,L-22-30-15-OP,2017-03-09 07:52:52,2017-03-09 07:53:33,4,13.666667,2017-03-09 07:52:25.500000,2017-03-09 07:53:50,0.0,0.0,0.0
25,BKWK90,F05,1,L-22-30-5-OP,2017-03-09 07:54:07,2017-03-09 07:54:10,2,3.000000,2017-03-09 07:53:50,2017-03-09 07:54:31,0.0,0.0,0.0
26,BKWK90,F05,1,L-22-16-25-SN,2017-03-09 07:54:52,2017-03-09 07:55:19,3,13.500000,2017-03-09 07:54:31,2017-03-09 07:56:35,0.0,0.0,0.0
27,BKWK90,F05,1,L-22-4-25-OP,2017-03-09 07:57:51,2017-03-09 07:57:57,3,3.000000,2017-03-09 07:56:35,2017-03-09 07:58:18,0.0,0.0,0.0
28,BKWK90,F05,1,L-22-4-15-OP,2017-03-09 07:58:39,2017-03-09 07:58:54,5,3.750000,2017-03-09 07:58:18,2017-03-09 07:59:35.500000,0.0,0.0,0.0
29,BKWK90,F05,1,L-22-4-5-OP,2017-03-09 08:00:17,2017-03-09 08:00:25,3,4.000000,2017-03-09 07:59:35.500000,2017-03-09 08:01:07,0.0,0.0,0.0
30,BKWK90,F05,1,L-24-6-17-OP,2017-03-09 08:01:49,2017-03-09 08:01:49,1,NaN,2017-03-09 08:01:07,2017-03-09 08:02:10,0.0,0.0,0.0
31,BKWK90,F05,1,L-24-6-16-OP,2017-03-09 08:02:31,2017-03-09 08:02:31,1,NaN,2017-03-09 08:02:10,2017-03-09 08:02:49,0.0,0.0,0.0
32,BKWK90,F05,1,L-24-6-11-OP,2017-03-09 08:03:07,2017-03-09 08:03:11,2,4.000000,2017-03-09 08:02:49,2017-03-09 08:03:34,0.0,0.0,0.0
33,BKWK90,F05,1,L-24-6-6-OP,2017-03-09 08:03:57,2017-03-09 08:03:57,1,NaN,2017-03-09 08:03:34,2017-03-09 08:05:06,0.0,0.0,0.0
34,BKWK90,F05,1,L-24-6-5-OP,2017-03-09 08:06:15,2017-03-09 08:06:15,1,NaN,2017-03-09 08:05:06,2017-03-09 08:06:29,0.0,0.0,0.0
35,BKWK90,F05,1,L-24-6-4-OP,2017-03-09 08:06:43,2017-03-09 08:07:08,4,8.333333,2017-03-09 08:06:29,2017-03-09 08:07:19,0.0,0.0,0.0
36,BKWK90,F05,1,L-24-6-3-OP,2017-03-09 08:07:30,2017-03-09 08:07:38,3,4.000000,2017-03-09 08:07:19,2017-03-09 08:07:59,0.0,0.0,0.0
37,BKWK90,F05,1,L-24-6-2-OP,2017-03-09 08:08:20,2017-03-09 08:08:34,3,7.000000,2017-03-09 08:07:59,2017-03-09 08:09:08.500000,0.0,0.0,0.0
38,BKWK90,F05,1,L-27-34-5-OP,2017-03-09 08:09:43,2017-03-09 08:10:19,4,12.000000,2017-03-09 08:09:08.500000,2017-03-09 08:17:19,0.0,0.0,0.0
39,BKWK90,F05,1,I-26-228-SN-25,2017-03-09 08:24:19,2017-03-09 08:24:19,1,NaN,2017-03-09 08:17:19,2017-03-09 08:28:26.500000,0.0,0.0,0.0
40,BKWK90,F05,1,L-26-35-20-PO,2017-03-09 08:32:34,2017-03-09 08:32:34,1,NaN,2017-03-09 08:28:26.500000,2017-03-09 08:34:04.500000,0.0,0.0,0.0
41,BKWK90,F05,1,T-26-224-NS-5,2017-03-09 08:35:35,2017-03-09 08:35:35,1,NaN,2017-03-09 08:34:04.500000,2017-03-09 08:36:19.500000,0.0,0.0,0.0
42,BKWK90,F05,1,L-24-6-2-PO,2017-03-09 08:37:04,2017-03-09 08:37:08,2,4.000000,2017-03-09 08:36:19.500000,2017-03-09 08:38:31.500000,1.0,2.0,0.0
43,BKWK90,F05,1,L-24-6-5-PO,2017-03-09 08:39:55,2017-03-09 08:39:55,1,NaN,2017-03-09 08:38:31.500000,2017-03-09 08:40:36.500000,1.0,1.0,0.0
44,BKWK90,F05,1,L-24-6-10-PO,2017-03-09 08:41:18,2017-03-09 08:41:18,1,NaN,2017-03-09 08:40:36.500000,2017-03-09 08:42:23.500000,1.0,3.0,1.0
45,BKWK90,F05,1,L-24-6-20-PO,2017-03-09 08:43:29,2017-03-09 08:43:29,2,0.000000,2017-03-09 08:42:23.500000,2017-03-09 08:47:40.500000,2.0,4.0,2.0
46,BKWK90,F05,1,L-22-3-25-NS,2017-03-09 08:51:52,2017-03-09 08:51:52,1,NaN,2017-03-09 08:47:40.500000,2017-03-09 08:54:02.500000,1.0,3.0,1.0
47,BKWK90,F05,1,L-33-6-60-NS,2017-03-09 08:56:13,2017-03-09 08:56:13,1,NaN,2017-03-09 08:54:02.500000,2017-03-09 08:56:37.500000,1.0,1.0,0.0
48,BKWK90,F05,1,L-33-6-70-NS,2017-03-09 08:57:02,2017-03-09 08:57:04,2,2.000000,2017-03-09 08:56:37.500000,2017-03-09 08:57:47.500000,0.0,0.0,0.0
49,BKWK90,F05,1,L-33-90-5-OP,2017-03-09 08:58:31,2017-03-09 08:58:31,1,NaN,2017-03-09 08:57:47.500000,2017-03-09 08:59:06.500000,0.0,0.0,0.0

In [ ]:
fig_1, ax_1 = plt.subplots()

ax_1.scatter(merged_turnstiles_df_noturns['diferencia_tiempo_secsmean'],merged_turnstiles_df_noturns['evasion_rate'])
ax_1.set_title('Evasion vs. Mean Time - No Turns, By Bus, Service, Stop, 20Secs')
ax_1.set_xlabel('Mean Time Interval [s]')
ax_1.set_ylabel('Evasion Rate [%]')

#plt.savefig('C:/Users/leoca_000/Desktop/Evasion/03_report/02_Figs/9_20Secs_EvasionVsMeanTimeByBusByServiceByStop.pdf')